# Specify a non-default branch for pull requests for npm

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to npm against the `development` branch
    target-branch: "development"
    # Labels on pull requests for version updates only
    labels:
      - "NPM Dependencies"
